# Example workflow configuration
repository:
  path: "/mnt/rbd/data/sftp/fair-crcc/"

sources:
  items:
  - some/directory/to/glob
  - another/individual/file.mrxs

keypair:
  private: bbmri-key
  public: bbmri-key.pub

output:
  format: ome-tiff
  compression: "JPEG-2000 Lossy"
  quality: 0.5 # at the moment only has an effect for JPEG-2000 Lossy
  tile_height: 4096
  tile_width: 4096
  max_cached_tiles: 256
