name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        snakemake-version: ["6.12.3"]
    steps:
    - uses: actions/checkout@v2

    - name: Install singularity
      run: |
        curl --output /tmp/singularity-ce.deb --location \
            https://github.com/sylabs/singularity/releases/download/v3.9.4/singularity-ce_3.9.4-focal_amd64.deb && \
        sudo apt update -y && \
        sudo apt install -y /tmp/singularity-ce.deb

    - name: debug tool execution
      shell: bash -l {0}
      run: |
        singularity  exec --home $PWD  --env TMPDIR=$PWD/img-convert-wf8xpu6asv docker://ilveroluca/bioformats2raw:0.3.1 bash -c "env | grep -i java"
        singularity  exec --home $PWD  --env TMPDIR=$PWD/img-convert-wf8xpu6asv docker://ilveroluca/bioformats2raw:0.3.1 bash -c "bioformats2raw -h"

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        mamba-version: "*"
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        miniforge-variant: "Mambaforge"
        miniforge-version: "4.11.0-0"
        use-mamba: true

    - name: mamba install dependencies
      shell: bash -l {0}
      run: |
        mamba install \
          snakemake-minimal==${{ matrix.snakemake-version }} \
          pytest

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -vs -o log_cli=true .tests/
